/**
 * Company API Services
 *
 * Este módulo contiene las funciones de API relacionadas con compañías.
 * Se utiliza para centralizar la lógica de negocio de compañías y mantener
 * una separación clara entre la lógica de API y los componentes de UI.
 *
 * @author Generated by Copilot
 * @since 2025-01-29
 */

"use server";

import { getCompanyByTenant } from "@/services/admin/company/services/company-service";

/**
 * Obtiene los datos básicos de una compañía por su tenant ID
 *
 * @param tenantId - El identificador único del tenant/compañía
 * @returns Objeto con los datos de la compañía (name, etc.)
 * @throws Error si la compañía no se encuentra
 */
export async function getCompanyData(tenantId: string) {
  try {
    const company = await getCompanyByTenant(tenantId);
    return {
      name: company.name,
      // Add other fields as needed
    };
  } catch (error) {
    console.error("Error fetching company:", error);
    throw new Error("Company not found");
  }
}