export type CountryConfig = {
  code: string; // ISO code
  name: string;
  currency: { code: string; symbol: string; locale: string };
  phone: { prefix: string; local: number; example: string; format?: string };
  locale: string;
  tax?: null | number;
  departments?: string[];
};

export const COUNTRY_CONFIGS: Record<string, CountryConfig> = {
  Argentina: {
    code: "AR",
    name: "Argentina",
    currency: { code: "ARS", symbol: "$", locale: "es-AR" },
    phone: {
      prefix: "54",
      local: 9,
      example: "54123456789",
      format: "XXX XXX XXX",
    },
    locale: "es-AR",
    tax: null,
    departments: [
      "Buenos Aires",
      "Catamarca",
      "Chaco",
      "Chubut",
      "Córdoba",
      "Corrientes",
      "Entre Ríos",
      "Formosa",
      "Jujuy",
      "La Pampa",
      "La Rioja",
      "Mendoza",
      "Misiones",
      "Neuquén",
      "Río Negro",
      "Salta",
      "San Juan",
      "San Luis",
      "Santa Cruz",
      "Santa Fe",
      "Santiago del Estero",
      "Tierra del Fuego",
      "Tucumán",
    ],
  },
  Bolivia: {
    code: "BO",
    name: "Bolivia",
    currency: { code: "BOB", symbol: "Bs", locale: "es-BO" },
    phone: {
      prefix: "591",
      local: 8,
      example: "59112345678",
      format: "XXXX XXXX",
    },
    locale: "es-BO",
    tax: null,
    departments: [
      "La Paz",
      "Cochabamba",
      "Santa Cruz",
      "Oruro",
      "Potosí",
      "Tarija",
      "Chuquisaca",
      "Beni",
      "Pando",
    ],
  },
  Chile: {
    code: "CL",
    name: "Chile",
    currency: { code: "CLP", symbol: "$", locale: "es-CL" },
    phone: {
      prefix: "56",
      local: 9,
      example: "56123456789",
      format: "XXX XXX XXX",
    },
    locale: "es-CL",
    tax: null,
    departments: [
      "Arica y Parinacota",
      "Tarapacá",
      "Antofagasta",
      "Atacama",
      "Coquimbo",
      "Valparaíso",
      "Metropolitana de Santiago",
      "Libertador General Bernardo O'Higgins",
      "Maule",
      "Ñuble",
      "Biobío",
      "La Araucanía",
      "Los Ríos",
      "Los Lagos",
      "Aysén del General Carlos Ibáñez del Campo",
      "Magallanes y de la Antártica Chilena",
    ],
  },
  Colombia: {
    code: "CO",
    name: "Colombia",
    currency: { code: "COP", symbol: "$", locale: "es-CO" },
    phone: {
      prefix: "57",
      local: 10,
      example: "571234567890",
      format: "XXX XXX XXXX",
    },
    locale: "es-CO",
    tax: null,
    departments: [
      "Amazonas",
      "Antioquia",
      "Arauca",
      "Atlántico",
      "Bolívar",
      "Boyacá",
      "Caldas",
      "Caquetá",
      "Casanare",
      "Cauca",
      "Cesar",
      "Chocó",
      "Córdoba",
      "Cundinamarca",
      "Guainía",
      "Guaviare",
      "Huila",
      "La Guajira",
      "Magdalena",
      "Meta",
      "Nariño",
      "Norte de Santander",
      "Putumayo",
      "Quindío",
      "Risaralda",
      "San Andrés y Providencia",
      "Santander",
      "Sucre",
      "Tolima",
      "Valle del Cauca",
      "Vaupés",
      "Vichada",
    ],
  },
  "Costa Rica": {
    code: "CR",
    name: "Costa Rica",
    currency: { code: "CRC", symbol: "₡", locale: "es-CR" },
    phone: {
      prefix: "506",
      local: 8,
      example: "50612345678",
      format: "XXXX XXXX",
    },
    locale: "es-CR",
    tax: null,
    departments: [
      "San José",
      "Alajuela",
      "Cartago",
      "Heredia",
      "Guanacaste",
      "Puntarenas",
      "Limón",
    ],
  },
  Cuba: {
    code: "CU",
    name: "Cuba",
    currency: { code: "CUP", symbol: "$", locale: "es-CU" },
    phone: {
      prefix: "53",
      local: 8,
      example: "5312345678",
      format: "XXXX XXXX",
    },
    locale: "es-CU",
    tax: null,
    departments: [
      "Pinar del Río",
      "Artemisa",
      "La Habana",
      "Mayabeque",
      "Matanzas",
      "Cienfuegos",
      "Villa Clara",
      "Sancti Spíritus",
      "Ciego de Ávila",
      "Camagüey",
      "Las Tunas",
      "Granma",
      "Holguín",
      "Santiago de Cuba",
      "Guantánamo",
      "Isla de la Juventud",
    ],
  },
  "El Salvador": {
    code: "SV",
    name: "El Salvador",
    currency: { code: "USD", symbol: "$", locale: "es-SV" },
    phone: {
      prefix: "503",
      local: 8,
      example: "50312345678",
      format: "XXXX XXXX",
    },
    locale: "es-SV",
    tax: null,
    departments: [
      "Ahuachapán",
      "Cabañas",
      "Chalatenango",
      "Cuscatlán",
      "La Libertad",
      "La Paz",
      "La Unión",
      "Morazán",
      "San Miguel",
      "San Salvador",
      "San Vicente",
      "Santa Ana",
      "Sonsonate",
      "Usulután",
    ],
  },
  Honduras: {
    code: "HN",
    name: "Honduras",
    currency: { code: "HNL", symbol: "L.", locale: "es-HN" },
    phone: {
      prefix: "504",
      local: 8,
      example: "50412345678",
      format: "XXXX XXXX",
    },
    locale: "es-HN",
    tax: null,
    departments: [
      "Atlántida",
      "Colón",
      "Comayagua",
      "Copán",
      "Cortés",
      "Choluteca",
      "El Paraíso",
      "Francisco Morazán",
      "Gracias a Dios",
      "Intibucá",
      "Islas de la Bahía",
      "La Paz",
      "Lempira",
      "Ocotepeque",
      "Olancho",
      "Santa Bárbara",
      "Valle",
      "Yoro",
    ],
  },
  Guatemala: {
    code: "GT",
    name: "Guatemala",
    currency: { code: "GTQ", symbol: "Q", locale: "es-GT" },
    phone: {
      prefix: "502",
      local: 8,
      example: "50212345678",
      format: "XXXX XXXX",
    },
    locale: "es-GT",
    tax: null,
    departments: [
      "Alta Verapaz",
      "Baja Verapaz",
      "Chimaltenango",
      "Chiquimula",
      "El Progreso",
      "Escuintla",
      "Guatemala",
      "Huehuetenango",
      "Izabal",
      "Jalapa",
      "Jutiapa",
      "Petén",
      "Quetzaltenango",
      "Quiché",
      "Retalhuleu",
      "Sacatepéquez",
      "San Marcos",
      "Santa Rosa",
      "Sololá",
      "Suchitepéquez",
      "Totonicapán",
      "Zacapa",
    ],
  },
  Nicaragua: {
    code: "NI",
    name: "Nicaragua",
    currency: { code: "NIO", symbol: "C$", locale: "es-NI" },
    phone: {
      prefix: "505",
      local: 8,
      example: "50512345678",
      format: "XXXX XXXX",
    },
    locale: "es-NI",
    tax: null,
    departments: [
      "Boaco",
      "Carazo",
      "Chinandega",
      "Chontales",
      "Estelí",
      "Granada",
      "Jinotega",
      "León",
      "Madriz",
      "Managua",
      "Masaya",
      "Matagalpa",
      "Nueva Segovia",
      "Rivas",
      "Río San Juan",
    ],
  },
  México: {
    code: "MX",
    name: "México",
    currency: { code: "MXN", symbol: "$", locale: "es-MX" },
    phone: {
      prefix: "52",
      local: 10,
      example: "521234567890",
      format: "XXX XXX XXXX",
    },
    locale: "es-MX",
    tax: null,
    departments: [
      "Aguascalientes",
      "Baja California",
      "Baja California Sur",
      "Campeche",
      "Chiapas",
      "Chihuahua",
      "Coahuila",
      "Colima",
      "Ciudad de México",
      "Durango",
      "Guanajuato",
      "Guerrero",
      "Hidalgo",
      "Jalisco",
      "México",
      "Michoacán",
      "Morelos",
      "Nayarit",
      "Nuevo León",
      "Oaxaca",
      "Puebla",
      "Querétaro",
      "Quintana Roo",
      "San Luis Potosí",
      "Sinaloa",
      "Sonora",
      "Tabasco",
      "Tamaulipas",
      "Tlaxcala",
      "Veracruz",
      "Yucatán",
      "Zacatecas",
    ],
  },
  Panamá: {
    code: "PA",
    name: "Panamá",
    currency: { code: "USD", symbol: "$", locale: "es-PA" },
    phone: {
      prefix: "507",
      local: 8,
      example: "50712345678",
      format: "XXXX XXXX",
    },
    locale: "es-PA",
    tax: null,
    departments: [
      "Bocas del Toro",
      "Coclé",
      "Colón",
      "Chiriquí",
      "Darién",
      "Herrera",
      "Los Santos",
      "Panamá",
      "Panamá Oeste",
      "Veraguas",
    ],
  },
  Paraguay: {
    code: "PY",
    name: "Paraguay",
    currency: { code: "PYG", symbol: "₲", locale: "es-PY" },
    phone: {
      prefix: "595",
      local: 9,
      example: "595123456789",
      format: "XXX XXX XXX",
    },
    locale: "es-PY",
    tax: null,
    departments: [
      "Asunción",
      "Concepción",
      "San Pedro",
      "Cordillera",
      "Guairá",
      "Caaguazú",
      "Caazapá",
      "Itapúa",
      "Misiones",
      "Paraguarí",
      "Alto Paraná",
      "Central",
      "Ñeembucú",
      "Amambay",
      "Canindeyú",
      "Presidente Hayes",
      "Alto Paraguay",
      "Boquerón",
    ],
  },
  "Puerto Rico": {
    code: "PR",
    name: "Puerto Rico",
    currency: { code: "USD", symbol: "$", locale: "es-PR" },
    phone: {
      prefix: "1",
      local: 10,
      example: "11234567890",
      format: "XXX XXX XXXX",
    },
    locale: "es-PR",
    tax: null,
    departments: [
      "Adjuntas",
      "Aguada",
      "Aguadilla",
      "Aguas Buenas",
      "Aibonito",
      "Añasco",
      "Arecibo",
      "Arroyo",
      "Barceloneta",
      "Barranquitas",
      "Bayamón",
      "Cabo Rojo",
      "Caguas",
      "Camuy",
      "Canóvanas",
      "Carolina",
      "Cataño",
      "Cayey",
      "Ceiba",
      "Ciales",
      "Cidra",
      "Coamo",
      "Comerío",
      "Corozal",
      "Culebra",
      "Dorado",
      "Fajardo",
      "Florida",
      "Guánica",
      "Guayama",
      "Guayanilla",
      "Guaynabo",
      "Gurabo",
      "Hatillo",
      "Hormigueros",
      "Humacao",
      "Isabela",
      "Jayuya",
      "Juana Díaz",
      "Juncos",
      "Lajas",
      "Lares",
      "Las Marías",
      "Las Piedras",
      "Loíza",
      "Luquillo",
      "Manatí",
      "Maricao",
      "Maunabo",
      "Mayagüez",
      "Moca",
      "Morovis",
      "Naguabo",
      "Naranjito",
      "Orocovis",
      "Patillas",
      "Peñuelas",
      "Ponce",
      "Quebradillas",
      "Rincón",
      "Río Grande",
      "Sabana Grande",
      "Salinas",
      "San Germán",
      "San Juan",
      "San Lorenzo",
      "San Sebastián",
      "Santa Isabel",
      "Toa Alta",
      "Toa Baja",
      "Trujillo Alto",
      "Utuado",
      "Vega Alta",
      "Vega Baja",
      "Vieques",
      "Villalba",
      "Yabucoa",
      "Yauco",
    ],
  },
  Perú: {
    code: "PE",
    name: "Perú",
    currency: { code: "PEN", symbol: "S/", locale: "es-PE" },
    phone: {
      prefix: "51",
      local: 9,
      example: "51123456789",
      format: "XXX XXX XXX",
    },
    locale: "es-PE",
    tax: null,
    departments: [
      "Amazonas",
      "Áncash",
      "Apurímac",
      "Arequipa",
      "Ayacucho",
      "Cajamarca",
      "Callao",
      "Cusco",
      "Huancavelica",
      "Huánuco",
      "Ica",
      "Junín",
      "La Libertad",
      "Lambayeque",
      "Lima",
      "Loreto",
      "Madre de Dios",
      "Moquegua",
      "Pasco",
      "Piura",
      "Puno",
      "San Martín",
      "Tacna",
      "Tumbes",
      "Ucayali",
    ],
  },
  Ecuador: {
    code: "EC",
    name: "Ecuador",
    currency: { code: "USD", symbol: "$", locale: "es-EC" },
    phone: {
      prefix: "593",
      local: 9,
      example: "593912345678",
      format: "XXX XXX XXX",
    },
    locale: "es-EC",
    tax: null,
    departments: [
      "Azuay",
      "Bolívar",
      "Cañar",
      "Carchi",
      "Chimborazo",
      "Cotopaxi",
      "El Oro",
      "Esmeraldas",
      "Galápagos",
      "Guayas",
      "Imbabura",
      "Loja",
      "Los Ríos",
      "Manabí",
      "Morona Santiago",
      "Napo",
      "Orellana",
      "Pastaza",
      "Pichincha",
      "Santa Elena",
      "Santo Domingo de los Tsáchilas",
      "Sucumbíos",
      "Tungurahua",
    ],
  },
  Uruguay: {
    code: "UY",
    name: "Uruguay",
    currency: { code: "UYU", symbol: "$", locale: "es-UY" },
    phone: {
      prefix: "598",
      local: 8,
      example: "59812345678",
      format: "XXXX XXXX",
    },
    locale: "es-UY",
    tax: null,
    departments: [
      "Artigas",
      "Canelones",
      "Cerro Largo",
      "Colonia",
      "Durazno",
      "Flores",
      "Florida",
      "Lavalleja",
      "Maldonado",
      "Montevideo",
      "Paysandú",
      "Río Negro",
      "Rivera",
      "Rocha",
      "Salto",
      "San José",
      "Soriano",
      "Tacuarembó",
      "Treinta y Tres",
    ],
  },
  Venezuela: {
    code: "VE",
    name: "Venezuela",
    currency: { code: "VES", symbol: "Bs.", locale: "es-VE" },
    phone: {
      prefix: "58",
      local: 10,
      example: "581234567890",
      format: "XXX XXX XXXX",
    },
    locale: "es-VE",
    tax: null,
    departments: [
      "Distrito Capital",
      "Amazonas",
      "Anzoátegui",
      "Apure",
      "Aragua",
      "Barinas",
      "Bolívar",
      "Carabobo",
      "Cojedes",
      "Delta Amacuro",
      "Falcón",
      "Guárico",
      "Lara",
      "Mérida",
      "Miranda",
      "Monagas",
      "Nueva Esparta",
      "Portuguesa",
      "Sucre",
      "Táchira",
      "Trujillo",
      "Vargas",
      "Yaracuy",
      "Zulia",
    ],
  },
};

export function getCountryConfigByName(name?: string) {
  if (!name) return undefined;
  // normalize common variants
  const normalized = name
    .normalize("NFD")
    .replace(/\p{Diacritic}/gu, "")
    .toLowerCase();
  return (
    Object.values(COUNTRY_CONFIGS).find(
      (c) =>
        c.name
          .normalize("NFD")
          .replace(/\p{Diacritic}/gu, "")
          .toLowerCase() === normalized
    ) ||
    Object.values(COUNTRY_CONFIGS).find((c) =>
      normalized.includes(c.name.toLowerCase())
    )
  );
}
